apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: my-app
  name: my-app-service
  namespace: demo
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp-8081-8080-my-app
      port: 8081
      protocol: TCP
      targetPort: 8080
  selector:
    k8s-app: my-app
  sessionAffinity: None
  type: LoadBalancer
